name: catkin_build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic
    steps:
      - name: Install basic requirements
        run: apt-get update && apt-get install -y git python3-catkin-tools

      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/mavlink_communicator

      - name: Install requirements
        run: ./catkin_ws/src/mavlink_communicator/install_requirements.sh

      - name: Catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build
